
package GUI;
import Process.*;



/**
 *
 * @author Anabell
 */
public class DirectMethodWindow extends javax.swing.JFrame 
{
    AccountingMath2 met = new AccountingMath2();

    /**
     * Creates new form NewJFrame
     */
    public DirectMethodWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jFormattedTextField17 = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jFormattedTextField18 = new javax.swing.JFormattedTextField();
        jFormattedTextField19 = new javax.swing.JFormattedTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jFormattedTextField20 = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jFormattedTextField21 = new javax.swing.JFormattedTextField();
        jFormattedTextField22 = new javax.swing.JFormattedTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jFormattedTextField23 = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jFormattedTextField24 = new javax.swing.JFormattedTextField();
        jFormattedTextField25 = new javax.swing.JFormattedTextField();
        jFormattedTextField26 = new javax.swing.JFormattedTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jFormattedTextField27 = new javax.swing.JFormattedTextField();
        jLabel32 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jFormattedTextField28 = new javax.swing.JFormattedTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Ventas = new javax.swing.JFormattedTextField();
        CostoUnitVentas = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        VentasNetas = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CostoVarProd = new javax.swing.JFormattedTextField();
        CostoVarOp = new javax.swing.JFormattedTextField();
        jSeparator2 = new javax.swing.JSeparator();
        CostoVarUnit = new javax.swing.JFormattedTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        InvInicial = new javax.swing.JFormattedTextField();
        ArtManuf = new javax.swing.JFormattedTextField();
        InvFinal = new javax.swing.JFormattedTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        CostoVarVenta = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        UtilidadNeta = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MargenContr = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        CostoFijoProd = new javax.swing.JFormattedTextField();
        CostoFijoAdm = new javax.swing.JFormattedTextField();
        CostoFijo = new javax.swing.JFormattedTextField();
        jSeparator13 = new javax.swing.JSeparator();
        Calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Ventas");
        jLabel9.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel9AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.add(jLabel9);
        jLabel9.setBounds(70, 60, 100, 20);

        jLabel19.setText("Costo de ventas unitario");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(30, 90, 130, 20);

        jFormattedTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField15ActionPerformed(evt);
            }
        });
        jPanel4.add(jFormattedTextField15);
        jFormattedTextField15.setBounds(280, 60, 80, 20);

        jFormattedTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField16ActionPerformed(evt);
            }
        });
        jPanel4.add(jFormattedTextField16);
        jFormattedTextField16.setBounds(280, 90, 80, 20);

        jLabel20.setText("VENTAS NETAS");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(50, 130, 80, 14);
        jPanel4.add(jSeparator5);
        jSeparator5.setBounds(230, 120, 170, 10);
        jPanel4.add(jFormattedTextField17);
        jFormattedTextField17.setBounds(280, 130, 80, 20);

        jLabel21.setText("Costo Fijo total de produccion");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(20, 180, 160, 14);

        jLabel22.setText("Produccion en unidades");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(40, 210, 113, 14);
        jPanel4.add(jLabel23);
        jLabel23.setBounds(80, 260, 0, 0);

        jLabel24.setText("Costo Fijo Unitario de produccion ");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(20, 250, 170, 20);
        jPanel4.add(jFormattedTextField18);
        jFormattedTextField18.setBounds(280, 180, 80, 20);

        jFormattedTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField19ActionPerformed(evt);
            }
        });
        jPanel4.add(jFormattedTextField19);
        jFormattedTextField19.setBounds(280, 210, 80, 20);
        jPanel4.add(jSeparator8);
        jSeparator8.setBounds(240, 240, 160, 10);
        jPanel4.add(jFormattedTextField20);
        jFormattedTextField20.setBounds(280, 250, 80, 20);

        jLabel25.setText("Costo variable unitario de produccion");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(20, 310, 190, 14);

        jLabel26.setText("Costo Fijo Unitario de produccion ");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(30, 340, 170, 14);
        jPanel4.add(jFormattedTextField21);
        jFormattedTextField21.setBounds(280, 310, 80, 20);
        jPanel4.add(jFormattedTextField22);
        jFormattedTextField22.setBounds(280, 340, 80, 20);
        jPanel4.add(jSeparator9);
        jSeparator9.setBounds(240, 372, 140, 0);
        jPanel4.add(jSeparator10);
        jSeparator10.setBounds(230, 370, 170, 10);

        jLabel27.setText("Costo de articulos manofacturados");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(20, 380, 180, 14);

        jFormattedTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField23ActionPerformed(evt);
            }
        });
        jPanel4.add(jFormattedTextField23);
        jFormattedTextField23.setBounds(280, 380, 80, 20);

        jLabel28.setText("Inventario Inicial");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(70, 440, 100, 14);

        jLabel29.setText("Costo articulos manofacturados");
        jPanel4.add(jLabel29);
        jLabel29.setBounds(30, 470, 152, 14);

        jLabel30.setText("Inventario Final");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(70, 500, 75, 14);

        jFormattedTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField24ActionPerformed(evt);
            }
        });
        jPanel4.add(jFormattedTextField24);
        jFormattedTextField24.setBounds(280, 430, 80, 20);

        jFormattedTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField25ActionPerformed(evt);
            }
        });
        jPanel4.add(jFormattedTextField25);
        jFormattedTextField25.setBounds(280, 460, 80, 20);
        jPanel4.add(jFormattedTextField26);
        jFormattedTextField26.setBounds(280, 490, 80, 20);
        jPanel4.add(jSeparator11);
        jSeparator11.setBounds(220, 520, 190, 10);

        jLabel31.setText("COSTO DE VENTAS");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(60, 530, 110, 14);
        jPanel4.add(jFormattedTextField27);
        jFormattedTextField27.setBounds(280, 530, 80, 20);

        jLabel32.setText("UTILIDAD BRUTA");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(70, 590, 100, 14);
        jPanel4.add(jSeparator12);
        jSeparator12.setBounds(170, 570, 280, 10);
        jPanel4.add(jFormattedTextField28);
        jFormattedTextField28.setBounds(285, 580, 80, 20);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel33.setText("  METODO DIRECTO");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(150, 30, 150, 14);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel34.setText("ESTADO DE RESULTADO");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(140, 10, 180, 18);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 551, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        jTabbedPane1.addTab("Cifras conocidas", jScrollPane2);

        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Ventas");
        jLabel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 120, 100, 20);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Costo de ventas unitario");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(60, 150, 150, 20);

        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        jPanel2.add(Ventas);
        Ventas.setBounds(300, 120, 80, 20);

        CostoUnitVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoUnitVentasActionPerformed(evt);
            }
        });
        jPanel2.add(CostoUnitVentas);
        CostoUnitVentas.setBounds(300, 150, 80, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("VENTAS NETAS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(70, 190, 120, 17);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(250, 180, 170, 10);

        VentasNetas.setEditable(false);
        jPanel2.add(VentasNetas);
        VentasNetas.setBounds(300, 190, 80, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Costo Variable Unitario de produccion");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 240, 220, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Costo Variable Unitario de operacion");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 270, 220, 17);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(80, 260, 0, 0);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Costo Variable Unitario");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 310, 160, 20);
        jPanel2.add(CostoVarProd);
        CostoVarProd.setBounds(300, 240, 80, 20);

        CostoVarOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoVarOpActionPerformed(evt);
            }
        });
        jPanel2.add(CostoVarOp);
        CostoVarOp.setBounds(300, 270, 80, 20);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(260, 300, 160, 10);

        CostoVarUnit.setEditable(false);
        jPanel2.add(CostoVarUnit);
        CostoVarUnit.setBounds(300, 310, 80, 20);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(240, 372, 140, 0);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Inventario Inicial");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(90, 380, 100, 17);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Costo articulos manofacturados");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(50, 410, 180, 17);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Inventario Final");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(90, 440, 120, 17);

        InvInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvInicialActionPerformed(evt);
            }
        });
        jPanel2.add(InvInicial);
        InvInicial.setBounds(300, 370, 80, 20);

        ArtManuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtManufActionPerformed(evt);
            }
        });
        jPanel2.add(ArtManuf);
        ArtManuf.setBounds(300, 400, 80, 20);
        jPanel2.add(InvFinal);
        InvFinal.setBounds(300, 430, 80, 20);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(240, 460, 190, 10);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("COSTO VARIABLE DE VENTA");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(40, 470, 190, 20);

        CostoVarVenta.setEditable(false);
        jPanel2.add(CostoVarVenta);
        CostoVarVenta.setBounds(300, 470, 80, 20);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("UTILIDAD NETA");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(80, 720, 130, 20);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(220, 500, 230, 10);

        UtilidadNeta.setEditable(false);
        jPanel2.add(UtilidadNeta);
        UtilidadNeta.setBounds(300, 720, 80, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("  METODO DIRECTO");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(150, 60, 150, 17);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("ESTADO DE RESULTADO");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(120, 30, 220, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("MARGEN DE CONTRIBUCION");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 520, 210, 17);

        MargenContr.setEditable(false);
        MargenContr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MargenContrActionPerformed(evt);
            }
        });
        jPanel2.add(MargenContr);
        MargenContr.setBounds(300, 520, 80, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Costo Fijo de Produccion");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 590, 150, 17);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Gasto Fijo de Administracion");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(50, 620, 180, 17);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setText("Costo Fijo");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(100, 670, 70, 17);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(210, 700, 250, 10);

        CostoFijoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoFijoProdActionPerformed(evt);
            }
        });
        jPanel2.add(CostoFijoProd);
        CostoFijoProd.setBounds(300, 590, 80, 20);
        jPanel2.add(CostoFijoAdm);
        CostoFijoAdm.setBounds(300, 620, 80, 20);

        CostoFijo.setEditable(false);
        CostoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoFijoActionPerformed(evt);
            }
        });
        jPanel2.add(CostoFijo);
        CostoFijo.setBounds(300, 670, 80, 20);
        jPanel2.add(jSeparator13);
        jSeparator13.setBounds(260, 650, 150, 10);

        Calcular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        jPanel2.add(Calcular);
        Calcular.setBounds(270, 790, 130, 23);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 551, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("Con precio Unitario", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4AncestorAdded

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VentasActionPerformed

    private void CostoUnitVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoUnitVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoUnitVentasActionPerformed

    private void CostoVarOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoVarOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoVarOpActionPerformed

    private void InvInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InvInicialActionPerformed

    private void ArtManufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtManufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArtManufActionPerformed

    private void jLabel9AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel9AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9AncestorAdded

    private void jFormattedTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField15ActionPerformed

    private void jFormattedTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField16ActionPerformed

    private void jFormattedTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField19ActionPerformed

    private void jFormattedTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField23ActionPerformed

    private void jFormattedTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField24ActionPerformed

    private void jFormattedTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField25ActionPerformed

    private void MargenContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MargenContrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MargenContrActionPerformed

    private void CostoFijoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoFijoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoFijoProdActionPerformed

    private void CostoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoFijoActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        AccountingMath2 met = new AccountingMath2();
        VentasNetas.setValue(met.Ventas());
        CostoVarUnit.setValue(met.CostoVariable());
        CostoVarVenta.setValue(met.CostoVariableDeVenta());
        MargenContr.setValue(met.Margen());
        CostoFijo.setValue(met.CostoFijo());
        UtilidadNeta.setValue(met.UtilidadNeta());
        
    }//GEN-LAST:event_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectMethodWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectMethodWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectMethodWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectMethodWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DirectMethodWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JFormattedTextField ArtManuf;
    private javax.swing.JButton Calcular;
    public static javax.swing.JFormattedTextField CostoFijo;
    public static javax.swing.JFormattedTextField CostoFijoAdm;
    public static javax.swing.JFormattedTextField CostoFijoProd;
    public static javax.swing.JFormattedTextField CostoUnitVentas;
    public static javax.swing.JFormattedTextField CostoVarOp;
    public static javax.swing.JFormattedTextField CostoVarProd;
    public static javax.swing.JFormattedTextField CostoVarUnit;
    public static javax.swing.JFormattedTextField CostoVarVenta;
    public static javax.swing.JFormattedTextField InvFinal;
    public static javax.swing.JFormattedTextField InvInicial;
    public static javax.swing.JFormattedTextField MargenContr;
    public static javax.swing.JFormattedTextField UtilidadNeta;
    public static javax.swing.JFormattedTextField Ventas;
    public static javax.swing.JFormattedTextField VentasNetas;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField20;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField23;
    private javax.swing.JFormattedTextField jFormattedTextField24;
    private javax.swing.JFormattedTextField jFormattedTextField25;
    private javax.swing.JFormattedTextField jFormattedTextField26;
    private javax.swing.JFormattedTextField jFormattedTextField27;
    private javax.swing.JFormattedTextField jFormattedTextField28;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    
}
