/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Anabell
 */
public class fileFrame extends javax.swing.JFrame {

    /**
     * Creates new form enterpriseMenu
     */
    public fileFrame() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLinkButton1 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton2 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton3 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton4 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton5 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton6 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton7 = new com.l2fprod.common.swing.JLinkButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLinkButton8 = new com.l2fprod.common.swing.JLinkButton();
        jLinkButton9 = new com.l2fprod.common.swing.JLinkButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLinkButton1.setText("Information");
        jPanel1.add(jLinkButton1);
        jLinkButton1.setBounds(0, 72, 240, 40);

        jLinkButton2.setText("New File");
        jPanel1.add(jLinkButton2);
        jLinkButton2.setBounds(0, 112, 240, 40);

        jLinkButton3.setText("Open File");
        jPanel1.add(jLinkButton3);
        jLinkButton3.setBounds(0, 150, 86, 24);

        jLinkButton4.setText("Save");
        jPanel1.add(jLinkButton4);
        jLinkButton4.setBounds(0, 180, 60, 24);

        jLinkButton5.setText("Save as");
        jPanel1.add(jLinkButton5);
        jLinkButton5.setBounds(0, 210, 77, 24);

        jLinkButton6.setText("Export");
        jPanel1.add(jLinkButton6);
        jLinkButton6.setBounds(0, 240, 68, 24);

        jLinkButton7.setText("Close");
        jPanel1.add(jLinkButton7);
        jLinkButton7.setBounds(0, 270, 63, 24);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 300, 120, 10);

        jLinkButton8.setText("User");
        jPanel1.add(jLinkButton8);
        jLinkButton8.setBounds(10, 320, 58, 24);

        jLinkButton9.setText("Options");
        jPanel1.add(jLinkButton9);
        jLinkButton9.setBounds(10, 350, 101, 24);

        jButton1.setText("<-}");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 30, 53, 25);

        jDesktopPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 160, 660);

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jDesktopPane1.add(jPanel2);
        jPanel2.setBounds(330, 60, 140, 130);

        jLabel1.setText("jLabel1");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(520, 80, 41, 16);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu m = new MainMenu();
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.l2fprod.common.swing.JLinkButton jLinkButton1;
    private com.l2fprod.common.swing.JLinkButton jLinkButton2;
    private com.l2fprod.common.swing.JLinkButton jLinkButton3;
    private com.l2fprod.common.swing.JLinkButton jLinkButton4;
    private com.l2fprod.common.swing.JLinkButton jLinkButton5;
    private com.l2fprod.common.swing.JLinkButton jLinkButton6;
    private com.l2fprod.common.swing.JLinkButton jLinkButton7;
    private com.l2fprod.common.swing.JLinkButton jLinkButton8;
    private com.l2fprod.common.swing.JLinkButton jLinkButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
